export const DEPARTMENTS = [
    'AAPI Studies',
    'Accounting',
    'American Sign Language Interpreting',
    'Anthropology',
    'Architecture',
    'Astronomy',
    'Biology',
    'Black Studies',
    'Building Construction Technology',
    'Business',
    'Culinary Arts',
    'Computer Business Technology',
    'Chemistry',
    'Chicana and Chicano Studies',
    'Child Development',
    'Chinese',
    'Computer and Information Science',
    'Communication Studies',
    'Dance',
    'Dentistry',
    'Dramatic Arts',
    'Economics',
    'Education',
    'Engineering',
    'English',
    'Exercise Science',
    'Fashion',
    'Fermentation Science',
    'Film',
    'Fine Arts',
    'French',
    'Geography',
    'Geology',
    'Geographic Information Systems',
    'German',
    'Health Education',
    'Health Information Technology',
    'Health Information Management',
    'History',
    'Hospitality',
    'Humanities',
    'Interior Design',
    'Italian',
    'Japanese',
    'Journalism',
    'Marketing',
    'Mathematics',
    'Medical Assisting',
    'Multimedia',
    'Music',
    'Nutrition',
    'Personal Growth',
    'Philosophy',
    'Physical Science',
    'Physical Therapy',
    'Physics',
    'Political Science',
    'Psychology',
    'Radiologic Technology',
    'Real Estate',
    'Russian',
    'Sociology',
    'Spanish',
    'Vietnamese',
    'Veterinary Technology',
    'Web Development'
    ];

    export const DEPARTMENT_OPTIONS = DEPARTMENTS.map(dept => ({ 
        value: dept,
        label: dept
    }));